services:

  

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    environment:
      - GATEWAY_PORT=9000
      - PRODUCT_SERVICE_HOST=product-service
      - PRODUCT_SERVICE_PORT=8080
      - ORDER_SERVICE_HOST=order-service
      - ORDER_SERVICE_PORT=8081
      - INVENTORY_SERVICE_HOST=inventory-service
      - INVENTORY_SERVICE_PORT=8082
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/devops-micro
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/devops-micro/protocol/openid-connect/certs
      - LOKI_HOST=loki
      - LOKI_PORT=3100
    ports:
      - "9000:9000"
    depends_on:
      - keycloak
      - product-service
      - order-service
      - inventory-service
    networks:
      - shared-network

  keycloak-db:
    image: mariadb:10.11
    container_name: keycloak-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - keycloak_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    restart: always
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://keycloak-db:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms:/opt/keycloak/data/import
    networks:
      - shared-network



#   frontend:
#     build:
#       context: ./microservices-shop-frontend
#       dockerfile: Dockerfile
#     container_name: frontend
#     ports:
#       - "4200:80"
#     networks:
#       - shared-network

# volumes:
#   keycloak_db_data:

# networks:
#   shared-network:
#     driver: bridge