kind: Deployment
apiVersion: apps/v1
metadata:
  name: product-mongo
  labels:
    app: product-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-mongo 
  template:
    metadata:
      labels:
        app: product-mongo
    spec:
      containers:
        - name: product-mongo
          image: mongo:7.0.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: DB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: DB_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: "product-service" 
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: product-mongo-pvc
