apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: default
  labels:
    app: product-service
type: Opaque
data:
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: cm9vdHBhc3N3b3JkZm9ybW9uZ28=
