apiVersion: v1
kind: Service
metadata:
  name: broker-headless
  labels:
    app: broker
spec:
  clusterIP: None
  ports:
    - name: kafka-internal
      port: 29092
      targetPort: 29092
  selector:
    app: broker
---
apiVersion: v1
kind: Service
metadata:
  name: broker-external
  labels:
    app: broker
spec:
  type: NodePort
  ports:
    - name: kafka-external
      port: 9092
      targetPort: 9092
      nodePort: 30092
  selector:
    app: broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
  labels:
    app: broker
spec:
  serviceName: broker-headless
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - name: internal
              containerPort: 29092
            - name: external
              containerPort: 9092
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://broker-0.broker-headless:29092,PLAINTEXT_HOST://$(NODE_IP):30092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "echo > /dev/tcp/localhost/29092"
            initialDelaySeconds: 10
            periodSeconds: 10