services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_service
    ports:
      - "8081:8081"
    environment:
      - DB_USERNAME=admin
      - DB_ROOT_PASSWORD=admin
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - INVENTORY_HOST=inventory_service
      - INVENTORY_PORT=8082
      - SERVER_PORT=8081
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - product-network

  mongo:
    image: mongo:7.0.5
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: product-service
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
     - product-network
  

networks:
  product-network:
    driver: bridge