kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory-deployment
  labels:
    app: inventory-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z mysql-inventory-service 3306; do echo waiting for mysql; sleep 2; done']
      containers:
        - name: inventory-container
          image: aymanaomarihub/inventory-service:v1.0.1
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: DB_HOST
              value: mysql-inventory-service
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: inventory-service
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secret
                  key: DB_PASSWORD
            - name: LOKI_HOST
              value: loki
            - name: LOKI_PORT
              value: "3100"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
            

            