kind: Deployment
apiVersion: apps/v1
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: mariadb:10.11
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: MYSQL_DATABASE
              value: "keycloak"
            - name: MYSQL_USER
              value: "keycloak"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: keycloak-db-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: keycloak-db-data
          persistentVolumeClaim:
            claimName: keycloak-db-pvc
