apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: default
data:
  realm.json: |
    {
      "realm": "devops-micro",
      "enabled": true,
      "clients": [
        {
          "clientId": "devops-micro-client",
          "enabled": true,
          "publicClient": true,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": false,
          "oauth2DeviceAuthorizationGrantEnabled": false,
          "redirectUris": [
            "http://localhost:4200/*",
            "http://localhost:9000/*",
            "http://*:4200/*",
            "http://*:9000/*"
          ],
          "webOrigins": [
            "http://localhost:4200",
            "http://localhost:9000",
            "*"
          ]
        }
      ]
    }
